# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-177e0abe-36c4-4165-be1e-d77cfe7abe16";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-177e0abe-36c4-4165-be1e-d77cfe7abe16".device = "/dev/disk/by-uuid/177e0abe-36c4-4165-be1e-d77cfe7abe16";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A49B-F767";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b0be0b35-9f41-43d5-a5c3-dc50cdd058a4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
